name: Test - AIML

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 3"

permissions:
  id-token: write
  contents: read

jobs:
  test-llm:
    uses: ./.github/workflows/module-test.yaml
    with:
      glob: aiml/chatbot
    secrets: inherit
